package relay

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"sync/atomic"
	"time"

	rootcommon "github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/logger"
	relaychannel "github.com/QuantumNous/new-api/relay/channel"
	relaycommon "github.com/QuantumNous/new-api/relay/common"
	relayconstant "github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/relaykit/dto"
	"github.com/QuantumNous/new-api/relaykit/types"
	"github.com/QuantumNous/new-api/service"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

type responsesWSUpstreamContextKey struct{}

// MarkResponsesWSUpstreamRequest marks only the internal POST generated by the
// authenticated downstream Responses WebSocket bridge. External request
// headers cannot forge this marker.
func MarkResponsesWSUpstreamRequest(ctx context.Context) context.Context {
	return context.WithValue(ctx, responsesWSUpstreamContextKey{}, true)
}

func IsResponsesWSUpstreamRequest(ctx context.Context) bool {
	marked, _ := ctx.Value(responsesWSUpstreamContextKey{}).(bool)
	return marked
}

func deriveResponsesWSURL(rawURL string) (string, error) {
	parsed, err := url.Parse(strings.TrimSpace(rawURL))
	if err != nil {
		return "", fmt.Errorf("parse responses websocket URL: %w", err)
	}
	switch strings.ToLower(parsed.Scheme) {
	case "https":
		parsed.Scheme = "wss"
	case "http":
		parsed.Scheme = "ws"
	case "ws", "wss":
		parsed.Scheme = strings.ToLower(parsed.Scheme)
	default:
		return "", fmt.Errorf("responses websocket URL must use http, https, ws, or wss")
	}
	if parsed.Host == "" {
		return "", fmt.Errorf("responses websocket URL must include a host")
	}
	return parsed.String(), nil
}

func normalizeResponsesWSCreatePayload(body []byte) ([]byte, error) {
	var payload map[string]json.RawMessage
	if err := json.Unmarshal(body, &payload); err != nil || payload == nil {
		return nil, fmt.Errorf("responses websocket payload must be a JSON object")
	}
	payload["type"] = json.RawMessage(`"response.create"`)
	delete(payload, "stream")
	return json.Marshal(payload)
}

var responsesWSUnsupportedCodes = map[string]struct{}{
	"websocket_not_supported":                     {},
	"unsupported_transport":                       {},
	"responses_websockets_disabled":               {},
	"responses_websockets_v2_disabled":            {},
	"websocket mode is disabled for this account": {},
}

func isResponsesWSUnsupported(statusCode int, body []byte, closeCode int) bool {
	switch statusCode {
	case 404, 405, 410, 426, 501:
		return true
	}
	if closeCode == 1003 {
		return true
	}
	if len(body) == 0 {
		return false
	}
	var value any
	decoder := json.NewDecoder(bytes.NewReader(body))
	decoder.UseNumber()
	if err := decoder.Decode(&value); err == nil && containsResponsesWSUnsupportedValue(value) {
		return true
	}
	text := strings.ToLower(strings.TrimSpace(string(body)))
	_, ok := responsesWSUnsupportedCodes[text]
	return ok || isResponsesWSUnsupportedText(text)
}

func isResponsesWSUnsupportedText(text string) bool {
	text = strings.ToLower(strings.TrimSpace(text))
	if !strings.Contains(text, "websocket") && !strings.Contains(text, "websockets") {
		return false
	}
	return strings.Contains(text, "not supported") || strings.Contains(text, "unsupported") || strings.Contains(text, "disabled")
}

func containsResponsesWSUnsupportedValue(value any) bool {
	switch typed := value.(type) {
	case map[string]any:
		for key, nested := range typed {
			if strings.EqualFold(key, "code") || strings.EqualFold(key, "type") || strings.EqualFold(key, "message") || strings.EqualFold(key, "reason") {
				if text, ok := nested.(string); ok {
					if _, exists := responsesWSUnsupportedCodes[strings.ToLower(strings.TrimSpace(text))]; exists {
						return true
					}
					if isResponsesWSUnsupportedText(text) {
						return true
					}
				}
			}
			if containsResponsesWSUnsupportedValue(nested) {
				return true
			}
		}
	case []any:
		for _, nested := range typed {
			if containsResponsesWSUnsupportedValue(nested) {
				return true
			}
		}
	}
	return false
}

func responsesWSCircuitAllows(disabledUntil int64, now time.Time) bool {
	return disabledUntil <= now.Unix()
}

func shouldUseResponsesWSUpstream(ctx context.Context, relayMode int, settings dto.ChannelSettings) bool {
	return relayMode == relayconstant.RelayModeResponses && settings.ResponsesWSUpstreamEnabled && IsResponsesWSUpstreamRequest(ctx)
}

func tryResponsesWSUpstream(c *gin.Context, info *relaycommon.RelayInfo, adaptor relaychannel.Adaptor, requestBody io.Reader) (*http.Response, bool, *types.NewAPIError) {
	now := time.Now()
	allowed, probe, disabledUntil := globalResponsesWSBreakerManager.begin(info.ChannelId, now)
	if !allowed {
		logger.LogInfo(c, fmt.Sprintf("responses upstream transport=http channel_id=%d reason=ws_circuit_open disabled_until=%d", info.ChannelId, disabledUntil))
		return nil, false, nil
	}

	replayable, ok := requestBody.(rootcommon.ReplayableBody)
	if !ok {
		globalResponsesWSBreakerManager.transient(info.ChannelId, probe, now)
		return nil, false, types.NewError(fmt.Errorf("responses websocket request body is not replayable"), types.ErrorCodeReadRequestBodyFailed, types.ErrOptionWithSkipRetry())
	}
	reader, err := replayable.NewReader()
	if err != nil {
		globalResponsesWSBreakerManager.transient(info.ChannelId, probe, now)
		return nil, false, types.NewError(err, types.ErrorCodeReadRequestBodyFailed, types.ErrOptionWithSkipRetry())
	}
	body, err := io.ReadAll(reader)
	_ = reader.Close()
	if err != nil {
		globalResponsesWSBreakerManager.transient(info.ChannelId, probe, now)
		return nil, false, types.NewError(err, types.ErrorCodeReadRequestBodyFailed, types.ErrOptionWithSkipRetry())
	}
	payload, err := normalizeResponsesWSCreatePayload(body)
	if err != nil {
		globalResponsesWSBreakerManager.transient(info.ChannelId, probe, now)
		return nil, false, types.NewError(err, types.ErrorCodeConvertRequestFailed, types.ErrOptionWithSkipRetry())
	}

	endpoint := strings.TrimSpace(info.ChannelSetting.ResponsesWSUpstreamURL)
	if endpoint == "" {
		httpEndpoint, urlErr := adaptor.GetRequestURL(info)
		if urlErr != nil {
			globalResponsesWSBreakerManager.transient(info.ChannelId, probe, now)
			return nil, false, types.NewError(urlErr, types.ErrorCodeDoRequestFailed)
		}
		endpoint, err = deriveResponsesWSURL(httpEndpoint)
		if err != nil {
			globalResponsesWSBreakerManager.transient(info.ChannelId, probe, now)
			return nil, false, types.NewError(err, types.ErrorCodeDoRequestFailed)
		}
	}

	headers := make(http.Header)
	if err := adaptor.SetupRequestHeader(c, &headers, info); err != nil {
		globalResponsesWSBreakerManager.transient(info.ChannelId, probe, now)
		return nil, false, types.NewError(err, types.ErrorCodeDoRequestFailed)
	}
	overrides, err := relaychannel.ResolveHeaderOverride(info, c)
	if err != nil {
		globalResponsesWSBreakerManager.transient(info.ChannelId, probe, now)
		return nil, false, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
	}
	for key, value := range overrides {
		headers.Set(key, value)
	}
	headers.Set("Content-Type", "application/json")
	headers.Set("Accept", "application/json")

	dialer, err := newResponsesWSDialer(info.ChannelSetting)
	if err != nil {
		globalResponsesWSBreakerManager.transient(info.ChannelId, probe, now)
		return nil, false, types.NewError(err, types.ErrorCodeDoRequestFailed)
	}
	logger.LogInfo(c, fmt.Sprintf("responses upstream transport=ws channel_id=%d endpoint=%s probe=%t", info.ChannelId, relaycommon.SanitizeURLForLog(endpoint), probe))
	response, unsupported, reason, err := dialResponsesWSStream(c.Request.Context(), dialer, endpoint, headers, payload)
	if unsupported {
		globalResponsesWSBreakerManager.unsupported(info.ChannelId, "unsupported_transport", truncateResponsesWSReason(reason), now)
		logger.LogWarn(c, fmt.Sprintf("responses upstream websocket disabled channel_id=%d disabled_until=%d reason=%s fallback=http", info.ChannelId, now.Add(24*time.Hour).Unix(), truncateResponsesWSReason(reason)))
		return nil, false, nil
	}
	if err != nil {
		globalResponsesWSBreakerManager.transient(info.ChannelId, probe, now)
		return nil, false, types.NewOpenAIError(err, types.ErrorCodeDoRequestFailed, http.StatusBadGateway)
	}
	return response, probe, nil
}

func newResponsesWSDialer(settings dto.ChannelSettings) (*websocket.Dialer, error) {
	transportSettings := settings
	transportSettings.HTTPProtocol = dto.HTTPProtocolHTTP1
	transportSettings.HTTP2ConnectionShards = 1
	client, err := service.GetHttpClientWithProxySettings(settings.Proxy, transportSettings)
	if err != nil {
		return nil, fmt.Errorf("create responses websocket transport: %w", err)
	}
	dialer := *websocket.DefaultDialer
	dialer.HandshakeTimeout = 10 * time.Second
	if transport, ok := client.Transport.(*http.Transport); ok && transport != nil {
		dialer.Proxy = transport.Proxy
		dialer.NetDialContext = transport.DialContext
		dialer.NetDialTLSContext = transport.DialTLSContext
		if transport.TLSClientConfig != nil {
			dialer.TLSClientConfig = transport.TLSClientConfig.Clone()
		}
	}
	return &dialer, nil
}

func completeResponsesWSUpstreamAttempt(channelID int, probe bool, response *http.Response, responseOK bool) {
	if !probe || response == nil {
		return
	}
	body, ok := response.Body.(*responsesWSStreamBody)
	if responseOK && ok && body.completed.Load() {
		globalResponsesWSBreakerManager.success(channelID, true)
		return
	}
	globalResponsesWSBreakerManager.transient(channelID, true, time.Now())
}

func truncateResponsesWSReason(reason string) string {
	reason = strings.TrimSpace(reason)
	reason = strings.Map(func(value rune) rune {
		if value == '\n' || value == '\r' || value == '\t' {
			return ' '
		}
		if value < 0x20 {
			return -1
		}
		return value
	}, reason)
	if len(reason) > 255 {
		return reason[:255]
	}
	return reason
}

// dialResponsesWSStream bridges a single upstream Responses WS turn into an
// HTTP/SSE-shaped response so the existing adaptor response parser and billing
// code remain the single source of truth.
func dialResponsesWSStream(ctx context.Context, dialer *websocket.Dialer, endpoint string, headers http.Header, requestBody []byte) (*http.Response, bool, string, error) {
	if dialer == nil {
		dialer = websocket.DefaultDialer
	}
	conn, handshakeResp, err := dialer.DialContext(ctx, endpoint, headers)
	if err != nil {
		if handshakeResp != nil {
			body, _ := io.ReadAll(io.LimitReader(handshakeResp.Body, 64<<10))
			_ = handshakeResp.Body.Close()
			if isResponsesWSUnsupported(handshakeResp.StatusCode, body, 0) {
				return nil, true, fmt.Sprintf("upstream websocket handshake status %d", handshakeResp.StatusCode), err
			}
		}
		return nil, false, "", err
	}
	conn.SetReadLimit(128 << 20)
	if err := conn.SetWriteDeadline(time.Now().Add(30 * time.Second)); err != nil {
		_ = conn.Close()
		return nil, false, "", err
	}
	if err := conn.WriteMessage(websocket.TextMessage, requestBody); err != nil {
		_ = conn.Close()
		return nil, false, "", fmt.Errorf("send response.create: %w", err)
	}
	if err := conn.SetReadDeadline(time.Now().Add(2 * time.Minute)); err != nil {
		_ = conn.Close()
		return nil, false, "", err
	}

	message, envelope, readErr := readResponsesWSDataMessage(conn)
	if readErr != nil {
		_ = conn.Close()
		closeCode := 0
		if closeErr, ok := readErr.(*websocket.CloseError); ok {
			closeCode = closeErr.Code
		}
		if isResponsesWSUnsupported(0, nil, closeCode) {
			return nil, true, fmt.Sprintf("upstream websocket close status %d", closeCode), readErr
		}
		return nil, false, "", readErr
	}
	if isResponsesWSUnsupported(http.StatusOK, message, 0) {
		_ = conn.Close()
		return nil, true, strings.TrimSpace(string(message)), fmt.Errorf("upstream explicitly rejected websocket transport")
	}
	if err := conn.SetReadDeadline(time.Time{}); err != nil {
		_ = conn.Close()
		return nil, false, "", err
	}

	streamContext, cancelStream := context.WithCancel(ctx)
	reader, writer := io.Pipe()
	streamBody := &responsesWSStreamBody{PipeReader: reader, cancel: cancelStream, conn: conn}
	done := make(chan struct{})
	go func() {
		select {
		case <-streamContext.Done():
			_ = conn.Close()
		case <-done:
		}
	}()
	go func() {
		defer close(done)
		defer cancelStream()
		defer conn.Close()
		if err := writeResponsesWSSSEEvent(writer, message); err != nil {
			_ = writer.CloseWithError(err)
			return
		}
		if isResponsesWSTerminalEvent(envelope.Type) {
			streamBody.completed.Store(true)
			_ = writer.Close()
			return
		}
		for {
			nextMessage, nextEnvelope, err := readResponsesWSDataMessage(conn)
			if err != nil {
				_ = writer.CloseWithError(err)
				return
			}
			if err := writeResponsesWSSSEEvent(writer, nextMessage); err != nil {
				_ = writer.CloseWithError(err)
				return
			}
			if isResponsesWSTerminalEvent(nextEnvelope.Type) {
				streamBody.completed.Store(true)
				_ = writer.Close()
				return
			}
		}
	}()

	return &http.Response{
		StatusCode: http.StatusOK,
		Header:     http.Header{"Content-Type": []string{"text/event-stream"}},
		Body:       streamBody,
	}, false, "", nil
}

type responsesWSEnvelope struct {
	Type string `json:"type"`
}

func readResponsesWSDataMessage(conn *websocket.Conn) ([]byte, responsesWSEnvelope, error) {
	for {
		messageType, message, err := conn.ReadMessage()
		if err != nil {
			return nil, responsesWSEnvelope{}, err
		}
		if messageType != websocket.TextMessage && messageType != websocket.BinaryMessage {
			continue
		}
		var envelope responsesWSEnvelope
		if err := json.Unmarshal(message, &envelope); err != nil {
			return nil, responsesWSEnvelope{}, fmt.Errorf("invalid upstream websocket event: %w", err)
		}
		return message, envelope, nil
	}
}

func writeResponsesWSSSEEvent(writer *io.PipeWriter, message []byte) error {
	if _, err := writer.Write([]byte("data: ")); err != nil {
		return err
	}
	if _, err := writer.Write(message); err != nil {
		return err
	}
	_, err := writer.Write([]byte("\n\n"))
	return err
}

type responsesWSStreamBody struct {
	*io.PipeReader
	cancel    context.CancelFunc
	conn      *websocket.Conn
	completed atomic.Bool
}

func (body *responsesWSStreamBody) Close() error {
	if body.cancel != nil {
		body.cancel()
	}
	if body.conn != nil {
		_ = body.conn.Close()
	}
	return body.PipeReader.Close()
}

func isResponsesWSTerminalEvent(eventType string) bool {
	switch strings.ToLower(strings.TrimSpace(eventType)) {
	case "response.completed", "response.done", "response.failed", "response.incomplete", "response.cancelled", "response.canceled", "response.error", "error":
		return true
	default:
		return false
	}
}
